### ISSUE TITLE
führende Null bei PLZ geht verloren

### ISSUE THREAD

**Issue by DirkThalheim** [ChrFr/qgis-geocoder#11]
Führende Nullen von PLZ gehen in der Verarbeitung verloren. Beim Aufruf des Geokodierungsdienstes kommen hierbei nur vierstellige PLZ beim Dienst an. Dies hat negativen Einfluss auf das Ergebnis und die Bewertung. Auch bei der Anzeige in der Attributtabelle sowie in der Karte werden die PLZ ohne führende 0 angezeigt.

Offenbar werden die PLZ als Zahlen interpretiert. Besser wäre es diese als String/Text vorzuhalten.

**Comment by ChrFr** [comment]
Es findet im Code keine Umwandlung statt, das passiert schon vorher beim Import. Da wir beim Klick auf "Daten laden" den QGIS-eigenen Dialog benutzen, habe wir programmatisch keinen Einfluss darauf, was dort passiert.

Man kann als Nutzer die Umwandlung des Feldes in Integer verhindern, indem man in dem Dialog unter "Datensatz- und Feldoptionen" die Checkbox "Feldtypen bestimmen" deaktiviert. Das ist natürlich nicht sehr leicht zu vermitteln

Alternativ kann ich Felder, die vom User dem Feld "Postleitzahl" zugeordnet, bei der Anfrage der Geocoding API in Strings umwandeln und Nullen davor hängen, wenn sie kürzer als 5 Characters sind. Ich würde das aber nicht in der Tabelle machen. Das würde merkwürdige Konsequenzen haben, wenn man sich mal verklickt (zB Feld mit Hausnummer versehentlich als Postleitzahl wählen und dann wieder zurück setzen)

**Comment by DirkThalheim** [comment]
Das Verhalten vom Standard-QGIS-Dialog spricht zusätzlich für den eigenen eigenen CSV-Whizard, der ja mit der finalen Version kommen soll. Ihren Hinweis zu den Feldtypen zum Standard-Dialog sollten wir in der Hilfe mit aufnehmen, wenn beschrieben wird Daten mit QGIS zu laden.

Den Vorschlag PLZ-Felder in der Geokodierung erst nach einer String-Formatierung zu nutzen finde ich gut. Das führt zumindest bei der Suche zu den richtigen Ergebnissen. Offen dabei bleibt dann vermutlich der Export. D.h. wenn die Daten wieder abgespeichert werden, gehen ggf. führende Nullen verloren. Lässt sich alternativ der Datentyp von Feldern eines Layers ändern? So könnte nach der Feldzuordnung das PLZ Feld in String konvertiert werden. Ansonsten müsste noch sichergestellt werden, dass im Ergebnislayer PLZ vom Typ String ist und die übernommenen PLZ-Daten 5 Stellen haben.

**Comment by ChrFr** [comment]
Ich würde von einer automatischen Umwandlung bei einem Wechsel der Feldzuordnung generell absehen. Das kann mehr kaputt machen als helfen, vor allem in Datenbanken (bei gesetztem "Layer aktualisieren".
Der Rest ist fertig
