### ISSUE TITLE
Attributzuweisung funktioniert nicht

### ISSUE THREAD

**Issue by DirkThalheim** [ChrFr/qgis-geocoder#12]
Im Testlauf hat die Attributzuweisung von CSV-Spalten zu Suchattributen nicht korrekt funktioniert. Für den Test A3.1-T1 wurde am Dienst folgender Query-Parameter geloggt:
  "4157" OR "Leipzig" OR "Gohlis-Mitte" OR "Lenaustraße" OR "9a"
bzw. URL Encodiert:
  query=%224157%22+OR+%22Leipzig%22+OR+%22Gohlis-Mitte%22+OR+%22Lenaustra%C3%9Fe%22+OR+%229a%22

Korrekt wäre:
  plz:(04157) OR ort:(Leipzig) OR ortsteil:(Gohlis-Mitte) OR strasse:(Lenaustraße) OR haus:(9a)

[A3.1-T1_adressen_mit-header_utf8_struktur_1.csv.zip](https://github.com/ChrFr/qgis-geocoder/files/4992931/A3.1-T1_adressen_mit-header_utf8_struktur_1.csv.zip)

**Comment by ChrFr** [comment]
gefixt zusammen mit #33
