### ISSUE TITLE
Möglichkeit zum request Debugging via Protokolle anbieten

### ISSUE THREAD

**Issue by DirkThalheim** [ChrFr/qgis-geocoder#14]
Zur einfacheren Fehleranalyse ist es hilfreich, wenn die Request an den Geokodierungsdienst protokolloiert werden und eingesehen werden können. Entweder sollte dies im Geocoder-Protokoll zu sehen sein oder in den QGIS-Logs. Es müsste eine erweiterte Einstellung sein, die nur bei Bedarf aktiviert werden kann.

**Comment by ChrFr** [comment]
Option in den Einstellungen>Expertenmodus den Debugmodus zu aktivieren. Alle Infos inkl. URL Ausgabe werden in den QGIS-Meldungen (der Knopf ganz rechts unten) ausgegeben.
Fehler werden ab jetzt immer da unten ausgegeben, auch bei deaktiviertem Debugmodus.
