### ISSUE TITLE
Datendialog nach Hinzufügen der Daten automatisch schließen.

### ISSUE THREAD

**Issue by DirkThalheim** [ChrFr/qgis-geocoder#15]
Wenn Daten über den Geocoder geladen werden, bleibt der Datendialog nach dem Hinzufügen geöffnet und fokosiert. Dies irritiert den Nutzer, da nicht offensichtlich ist, dass die ausgewählten Daten QGIS und dem Geocoder hinzugefügt wurden. Evtl. erledigt sich dies, wenn ein eigener CSV-Datendialog implementiert wurde.

**Comment by ChrFr** [comment]
Richtig, dazu müssten wir einen eigenen Dialog implementieren.
Der QGIS-Dialog kann nicht vom Plugin-Code aus gesteuert und geschlossen werden.

**Comment by DirkThalheim** [comment]
Der eigene Dialog sollte Teil der finalen Version sein. Damit sollte sich die Issue erledigen.
