### ISSUE TITLE
Excel-Dateien: "Header-Zeile" wird als Datenzeile interpretiert.

### ISSUE THREAD

**Issue by DirkThalheim** [ChrFr/qgis-geocoder#16]
Beim Laden von Excel-Dateien wird eine vorhandene Header-Zeile (=Zeile mit Spaltennamen) als Datenzeile interpretiert und geokodiert. Diese sollte übersprungen werden.

**Comment by DirkThalheim** [comment]
Beispieldatensatz:
[A3.5-T2_adressen_utf8.xlsx.zip](https://github.com/ChrFr/qgis-geocoder/files/4993025/A3.5-T2_adressen_utf8.xlsx.zip)

**Comment by ChrFr** [comment]
QGIS bietet bei Exceldateien leider nicht wir bei CSV die Möglichkeit, die Header zu definieren und nimmt per default an, dass es keine Headerzeile gibt.

Entweder belassen es dabei und der Nutzer muss die Zeile rauslöschen bzw. alle anderen Zeilen markieren und nur markierte Zeilen geokodieren, oder wir müssen einen eigenen Importdialog bauen.

**Comment by DirkThalheim** [comment]
Einen eigenen Importdialog halte ich für zu aufwändig. Dann sollten wir das entsprechend in der Hilfe dokumentieren. Es schadet vermutlich nicht wenn die erste Zeile dennoch geokodiert wird. Anonsten könnte alternativ noch eine Option im Expertenmodus angeboten werden, die besagt, die erste Zeile des Quelllayers zu ignorieren.
