### ISSUE TITLE
Fehlermeldung bei ungültigem RS

### ISSUE THREAD

**Issue by DirkThalheim** [ChrFr/qgis-geocoder#17]
Werden ungültige Regionalschlüssel zur Sucheinschränkung angegeben, dann erscheint keine Fehlermeldung bzw. es treten unerwartete Ergebnisse auf. Hier sollte die Eingabe gegen eine Regex (z.B. `[01]\d+`) geprüft werden.

Fehlerhafte Beispiele mit denen getestet wurde:
  - bremen
  - o4*
  - 99*
  - 04-0-110-0

**Comment by ChrFr** [comment]
Ich hätte erwartet, dass da die Schnittstelle meckert. Ich werde versuchen einen brauchbaren regex-Ausdruck zu finden. Ist schwierig wegen des Sterns, der ja an jeder Stelle kommen kann.

**Comment by DirkThalheim** [comment]
Wie wäre es mit dieser Regex: `[01]\d{0,11}\*?`

**Comment by ChrFr** [comment]
Danke, der reguläre Ausdruck passt. Die Prüfung erfolgt bei Eingabe (Anzeige bei Fehler in label) und der Schlüssel wird mit einer Fehelrmeldung ignoriert beim Geocoden.
