### ISSUE TITLE
Räumlicher Filter mit komplexen Geometrien erzeugt zu lange URI

### ISSUE THREAD

**Issue by DirkThalheim** [ChrFr/qgis-geocoder#19]
Der Test der räumlichen Sucheinschränkung konnte nicht durchgeführt werden, da die generierte URL zu lang wurde. Im Test wurden z.B. die Verwaltungsgrenzen von Bremen oder Berlin verwendet. Die Abbildung als WKT scheint hier zu lang zu werden. Das Problem könnte mit einem POST-Request umgangen werden. Leider unterstützt die Schnittstelle derzeit nur GET.

Es müsste also aktuell geprüft werden, ob die selektierte Geometrie überhaut verwendet werden darf und entsprechende Hinweise ausgegeben werden.

**Comment by ChrFr** [comment]
Die maximale Länge der URL ist serverseitig konfiguriert, oder? Wie lang darf oder sollte denn die URL bzw. der Parameter momentan werden? 
Wir könnten auch die Geometrien automatisch vereinfachen, aber das wäre vermutlich unerwartet für den Nutzer und würde unerwartete Ergebnisse produzieren.

**Comment by DirkThalheim** [comment]
Die exakte Länge kann ich nicht genau bestimmen. Eine kurze Recherche hat pro Forma 2000 Zeichen ergeben: https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

Ich denke es ist besser bei Geometrie-Operationen auf POST umzuschwenken. Dazu müssten wir zunächst noch POST im Geokodierungsdienst aktivieren. Dies werden wir mit hoher Priorität angehen.

**Comment by ChrFr** [comment]
Die Länge ist sicherheitshalber auf 1500 Zeichen limitiert um noch Platz für die restlichen Queryparameter zu lassen. Das ist wirklich nicht besonders viel. Viel mehr als Rechtecke gehen da nicht.

Die Prüfung erfolgt bei Auswahl des Filterlayers und bei Klicken auf eine der Checkboxen. In der BKG-Oberfläche wird angezeigt, falls die Geometrie zu komplex ist und bei Ausführung gibt es dann eine Warnung im Log und die Geometrie wird ignoriert.

Es gibt keine Verbindung zu dem zur Filterung gewählten Layer. Wenn man da was dran ändert (Auswahl ändern, Features hinzu, löschen, verändern) kriegt das die BKG-Oberfläche erstmal nicht mit. Es betrifft zu viele Signale, die immer wieder an- und abgemeldet werden müssten bei Layerwechsel, so dass es zu unübersichtlich werden und Fehler provozieren würde.

Dafür gibt es einen Reloadbutton neben der Layerauswahl und die Überprüfung erfolgt nochmal beim Start der Geokodierung (und wie oben erwähnt beim Klicken auf irgendwelche Schaltflächen des Filters).
