### ISSUE TITLE
Fehleranzeige fehlende Zugriffsrechte optimieren

### ISSUE THREAD

**Issue by DirkThalheim** [ChrFr/qgis-geocoder#21]
Aktuell wird im Protokoll nur Falsche UUID vermerkt. Besser wäre "Falsche UUID oder fehlende Zugriffsrechte auf den Geokodierungsdienst". Ggf. Anzeige in Warndialog verlagern. Fehlermeldung/Fehlercode des Dienstes sollte mit ausgeben werden (z.B. ERROR_UKNONW_IDENT).

**Comment by ChrFr** [comment]
Meldung ist angepasst, zusätzlich wird die UUID auch schon in der Konfiguration geprüft. Deswegen mache ich erstmal keine Meldung in einem Dialog dafür (würde nicht in die derzeitige Fehlerbahandlung passen)
