### ISSUE TITLE
Eingabe- und Ergebnislayer nicht gesperrt beim Durchlauf

### ISSUE THREAD

**Issue by DirkThalheim** [ChrFr/qgis-geocoder#26]
Eingabe- und Ergebnislayer werden beim Geokodierungsdurchlauf nicht gesperrt. D.h. sie sind editierbar. Dies erlaubt versehentliche Editierungen, die das Geokodierungsergebnis korrumpieren können.

**Comment by ChrFr** [comment]
Ich habe eine Sperre eingebaut in den Edit-Modus zu gehen während des Geocodings. Wenn man sich allerdings bereits im Edit-Modus eines Layers befindet, kann man auch weiterhin editieren. Verlässt man diesen nämlich, müssen entweder alle Änderungen commited oder verworfen werden. Keines von beiden ist etwas, was man ungefragt machen sollte.

Auch können die Eingabe-/Ausgabelayer weiterhin gelöscht werden während des laufenden Geocodings. Das lässt sich nicht verhindern. Ich habe eingebaut, dass das Geocoding dann abgebrochen wird mit einer Fehlermeldung.

**Comment by DirkThalheim** [comment]
Ok, das klingt soweit gut. Vielleicht weißen wir in der Dokumentation nochmal darauf hin Änderungen an den Layern während der Geokodierung zu vermeiden.
