### ISSUE TITLE
Nicht alle Ergebnisattribute stehen im Ergebnislayer zur Verfügung

### ISSUE THREAD

**Issue by DirkThalheim** [ChrFr/qgis-geocoder#32]
Momentan wird nur text, score, bkg_n_result, bkg_treffer, manuell_bearbeitet ergänzt. Es sollte die Möglichkeit bestehen weitere Attribute des Datenmodells in den Ergebnislayer/Ausgabedatei zu übernehmen.

**Comment by ChrFr** [comment]
Sind die Attribute 'ags', 'schluessel', 'bundesland', 'gemeinde' usw. gemeint, die die gefundene Adresse beschreiben? 
Ich kann die alle auf Verdacht in den Layer speichern (mit Zusatz "laut Dienst"), aber das wäre der Übersichtlichkeit nicht dienlich.

Wenn der Nutzer die zusätzlichen Attribute auswählen soll, wüsste ich jetzt nicht auf Anhieb wohin damit ohne die Oberfläche zu überfrachten. Es müssten (viele, 15?) Checkboxen irgendwo platziert werden. Wir können das aufklappbar in die Konfiguration packen mit der Überschrift "zusätzliche Ergebnisfelder" oder so ähnlich

**Comment by DirkThalheim** [comment]
Es sind alle Attribute des Datenmodells gemeint (vgl. http://sg.geodatenzentrum.de/public/gdz/dokumentation/deu/geokodierungsdienst.pdf Kapitel 2.1), ausgenommen `name` und `kategorie `(die betreffen nur Objekte vom Typ Geoname). Ich stimme zu, dass dies unübersichtlich werden kann. Hierfür wäre es sinnvoll in der erweiterten Einstellungen die zu übernehmenden Attribute per Checkbox auszuwählen. Minimal sollten `plz`, `ort`, `ortsteil`, `strasse`, `haus`, `typ`, `score`, `treffer`, und `rs `zur Übernahme aktiviert sein. Im Ergebnislayer kann für die übernommenen Attribute das Prefix `gc_` verwendet werden, um Komplikationen mit vorhandenen Attributen zu vermeiden.
