### ISSUE TITLE
Objektzoom nicht ausreichend

### ISSUE THREAD

**Issue by DirkThalheim** [ChrFr/qgis-geocoder#52]
Beim Zoomen auf einen Eintrag in der Ergebnistabelle über Zoom-Button wird nicht weit genug "hereingezoomt". Dies ist insbesondere bei mehreren, nahe beieinander liegenden Ergebnissen unpraktisch/verwirrend. Kann dies optimiert werden? Im Datenmodell des Dienstes wird neben der Mittelpunktskoordinate auch eine BBOX mitgegeben. Sofern diese in QGIS verfügbar ist, könnte diese für den Zoom verwendet werden. Ansonsten besteht die Möglichkeit den Zoom auf Basis des Typs festzulegen.

**Comment by ChrFr** [comment]
Das ist leider wieder eine QGIS-Funktionalität, auf die ich keinen Einfluss habe (behaupte ich mal). Ich kriege leider keine eigenen Funktionen, die sich auf ein angeklicktes Feature beziehen, in die Ergebnistabelle rein (geht nur mit externen Skripten komischerweise). Deswegen kann ich auch leider nicht die Funktion "Ergebnis inspizieren" direkt in die Tabelle einbinden.

Ich gucke mir das nochmal an, aber ich befürchte, das wird nichts.
