### ISSUE TITLE
Probleme mit Zurücksetzen des QGIS-Projekts

### ISSUE THREAD

**Issue by DirkThalheim** [ChrFr/qgis-geocoder#53]
Wird nach einer   erfolgten Geokodierung ein neues Projekts in QGIS  geöffnet (Projekt --> Neu), wird das Plugin nicht richtig initialisiert:      
- die Hintergrundkarte wird nicht automatisch geladen
- der Zustand des letzten Laufes ist erhalten geblieben. 

Insbesondere das Feld-Mapping sollte zurüpckgesetzt werden.

**Comment by ChrFr** [comment]
Mir ist kein Signal bekannt, das ausgelöst wird bei Erzeugung eines Projekts. Das Plugin wird nicht bei Erzeugung eines Projektes initialisiert, sondern beim erstmaligen Öffnen. Ich fände es seltsam, wenn der Geocoder immer die Hintergrundkarten reinlädt, wenn man ein neues Projekt erstellt, auch wenn er gerade gar nicht mehr benutzt werden soll.  

Stattdessen sind Funktionen angemeldet auf das Löschen von Eingangs- und Ausgangslayern, um die Oberfläche zurückzusetzen. Das wird auch bei neuen Projekten getriggert. Das Zurücksetzen des Feld-Mappings war noch nicht drin, das habe ich jetzt zusätzlich eingebaut (beim Löschen des Inputs).

Was ich bezüglich der Hintergrundkarten gemacht habe: sie werden jetzt reingeladen, wenn das Plugin geöffnet wird und die Karten noch nicht da sind. Wenn man das Plugin schließt und wieder öffnet, erscheinen sie wieder, falls sie entfernt wurden.  Man könnte die Karten auch reinladen, wenn man einen neuen Input auswählt.
Das ist eventuell nervig, wenn man die Karten gar nicht haben will und löscht, sie aber trotzdem immer wieder reingeladen werden. 
Ich könnte auch einen extra Knopf einbauen, mit dem man die Hintergrundkarten manuell laden kann.

**Comment by DirkThalheim** [comment]
Den Vorschlag mit dem separaten Button zum Laden der Hintergrundkarte finde ich gut. Dies würde erfahrenen GIS-Nutzern entgegen kommen, die ihre eigenen Hintergrundkarten verwenden wollen. Der Button könnte wie folgt positioniert sein:
* Im Tab Eingeabedaten: Damit wäre er gleich zu Beginn gut sichtbar, würde aber semantisch nicht ganz passen.
* Im Tab Ergebnis: Das würde semantisch besser passen, damit wäre der Button aber erst bei der Durchführung der Geokodierung sichtbar.
* Am unteren Rand: Immer gut sichtbar, könnte aber ggf. die Leiste "überfrachten".

**Comment by ChrFr** [comment]
Nach etwas Überlegung:
Wäre es eventuell sinnvoller die Karten nur beim Start einer Anfrage zu laden? In der Konfiguration könnte man eine Checkbox  "automatisch Hintergrundkarten laden" im Konfigurations-Tab unter Expertenmodus einfügen, die standardmäßig aktiviert ist. Den zusätzlichen Button könnte man dann weglassen.

**Comment by DirkThalheim** [comment]
Das finde ich auch in Ordnung
