### ISSUE TITLE
Automatische Feldzuweisung erkennt str. nicht

### ISSUE THREAD

**Issue by DirkThalheim** [ChrFr/qgis-geocoder#54]
Im [Testdatensatz](https://github.com/ChrFr/qgis-geocoder/files/5635397/data.txt) wird ‚str.‘ nicht automatisch Straße zugeordnet.

**Comment by ChrFr** [comment]
Sollte es? War mir nicht bekannt.

Was erkannt wird, sind nur die 'pretty' Namen ('Straße' in dem Fall) und das keyword der API (in dem 'strasse') ungeachtet der Großbuchstaben, aber keine Abkürzungen oder weitere Aliase.

Ich müsste irgendwas implementieren, um alle möglichen Aliase zu mappen. Das kann man dann auch ins Absurde treiben.
Im Fall von Straße (neben der vorhandenen auto Zuweisung): 

- str
- str.
- strassenname
- straßenname 
- street (naja gut englisch vielleicht nicht)

Regex wird da nicht funktionieren ("fängt mit str an" ist nicht gut, glaube ich). 

Ist das wirklich nötig?

**Comment by DirkThalheim** [comment]
Ich würde es zunächst nur auf die Abkürzung von Straße beschränken. Eine vereinfachte Regex (case-insensitive) könnte sein
```
^str(\.?|a[s|ß]+e)$
```

**Comment by ChrFr** [comment]
Guter Vorschlag. Wir haben jetzt reguläre Ausdrücke für (fas)t alle keywords eingebaut.
