### ISSUE TITLE
Tippfehler in Kategorie

### ISSUE THREAD

**Issue by DirkThalheim** [ChrFr/qgis-geocoder#61]
Liefert der Dienst in einer Kategorie (zusätzliche Ergebnisfelder) leere Ergebnisse, wird in die Ergebnistabelle 'unbesezt' statt 'unbesetzt' geschrieben.

**Comment by ChrFr** [comment]
Liegt der Fehler eventuell beim Dienst? Ich finde weder in den Styles noch im Code des Plugins einen Zeichenstring "unbesezt" (außer in einem Testfile, aber das wurde aus den Antworten des Dienstes erzeugt)

**Comment by DirkThalheim** [comment]
Den Fehler kann ich aktuell nicht mehr nachstellen. Anscheinend hat sich dies auf eine ältere Version des Plugins bezogen. Es trat auf, wenn im Ergebnis ein Feld/Attribut nicht besetzt war. Aktuell wird hier NULL angezeigt, was in Ordnung ist.
