### ISSUE TITLE
Daten Laden Dialog nicht vollständig gefüllt

### ISSUE THREAD

**Issue by DirkThalheim** [ChrFr/qgis-geocoder#62]
Beim erneuten   Öffnen des Daten Laden Dialogs (Datenquellenverwaltung), ist die rechte Seite nicht komplett gefüllt (s. Screenshot). Nur die Änderung der Fenstergröße füllt alles und die Dateioptionen werden sichtbar.

Lässt sich das über das Geocoder-Plugin kontrollieren?

![Datenquellenverwaltung](https://user-images.githubusercontent.com/7570459/100999595-402f3b80-355d-11eb-91d8-0a42a6078451.png)

**Comment by ChrFr** [comment]
Leider nicht, das ist ein Bug in QGIS. In 3.14 taucht der Fehler bei mir nicht mehr auf.
